name: docker-health-check

services:
  docker-health-check:
    image: rcolfin/metelsoft:docker-health-check
    container_name: docker-health-check
    pull_policy: always
    restart: unless-stopped

    build:
      context: ../..
      dockerfile: docker-health-check/docker/Dockerfile
      tags:
        - rcolfin/metelsoft:docker-health-check
        - rcolfin/metelsoft:docker-health-check${TAG:+-${TAG}}
      args:
        BUILD_DATE: ${BUILD_DATE:-}
        GIT_COMMIT: ${GIT_COMMIT:-unknown}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    command:
      - --interval
      - "30"
      - --label
      - "com.dockerhealthcheck.enable=true"

    environment:
      HOSTNAME: "${HOSTNAME}"
